### PR TITLE
Add cache and sccache

### PR DESCRIPTION
**Pull request by martadinata666**
From my test it just shaved about 2~3 mnites. Not so impressive.

### CODE REVIEW

**Comment by nitnelave** [comment]
Hmm, that's interesting, but I was more thinking about caching the workflow steps: can we use docker-like caching of steps for installing npm, cargo, wasm-pack and so on? If they jump directly into the docker step with exactly the same context, the cache is going to apply and we'll save a lot, especially with the dependencies. And we can use cargo chef to precompile the dependencies and cache that

**Comment by martadinata666** [comment]
Im not really familiar with directory structure of rust, according to this we can also cache `target` dir, https://doc.rust-lang.org/cargo/guide/build-cache.html.

About chef, like your maik dockerfile? Cargo chef cook? Well we can just try what works or not. Sccache told reduce compiling seems not right 😂

**Comment by martadinata666** [comment]
This should be sufficient, caching sccache, target, cargo. Minimal download. on first build will pretty slow due first cache creation, pretty big, almost 1GB 😱

**Comment by nitnelave** [comment]
Normally, it should pick up the changes in cargo.toml and recompile. Hopefully it doesn't always recompile just because the context is different. We'll have to see, but let's start with your change, it's already much better, thanks!

**Pull request merged**
