### PR TITLE
Build script

### LINKED ISSUE #3: Build Script Fails
## Expected Behavior
Build script completes without errors.

## Actual Behavior
Build fails. I suspect this is because i do not have npm in my path or something.

```
$ ./app/build.sh 
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
    Finished release [optimized] target(s) in 0.05s
:-) [WARN]: origin crate has no README
[INFO]: Installing wasm-bindgen...
[INFO]: Optimizing wasm binaries with `wasm-opt`...
[INFO]: Optional fields missing from Cargo.toml: 'description', 'repository', and 'license'. These are not necessary, but recommended
[INFO]: :-) Done in 9.53s
[INFO]: :-) Your wasm pkg is ready to publish at /home/jermz/projects/lldap-original/app/pkg.
./app/build.sh: 5: rollup: not found
```

## Steps to Reproduce the Problem

  1. Start up a new linux VM
  2. Clone Repo
  3. cd into directory
  4. Install Rust
  5. Follow instructions on README.md
  

## Specifications

  - Version: N/A
  - Platform: Linux   ##(amd64)
  - Subsystem: Debian Sid

### PR DESCRIPTION
**Pull request by anomalyze**
This update fixes #3 the build script failing if you complete the 'npm install rollup' from within the main directory

### CODE REVIEW

**Comment by anomalyze** [comment]
Sorry i think i added too many commits here

**Comment by nitnelave** [comment]
Sure, but it breaks it if you _didn't_ install it there :)
It seems easier to bring that folder into your `PATH` than to make everyone install it there. I'm open to other ideas of how to handle this, though.

**Comment by anomalyze** [comment]
By default the npm install command installs to the [current working directory](https://nodejs.dev/learn/where-does-npm-install-the-packages/)

I followed the instructions from the README.md and had that problem. Hopefully, helps future users.

**Comment by nitnelave** [comment]
I pushed a new version of the build script, that should take care of the local/global install issue. If that fixes the problem for you, feel free to close this PR.

**Pull request closed without merging**
