### PR TITLE
Remove sccache, cache key using cargo lock hash

### PR DESCRIPTION
**Pull request by martadinata666**
add cargo update, check sccache show stats to see if it caching correctly

### CODE REVIEW

**Comment by martadinata666** [comment]
Just removed sccahe, and reset cache if cargo.lock changes.

**Comment by nitnelave** [comment]
This is out of date, no?

**Comment by martadinata666** [comment]
No, this still stands for non-static build. As currently still using github sha instead cargo.lock.

**Comment by nitnelave** [comment]
Yeah, let's simplify, drop the debian build, and keep just the alpine one (let's remove `-alpine` from the tags).

Also, could you partly restore the docker build using the top-level Dockerfile, to make sure that people can still build their own docker image if they want? Without pushing to DockerHub

**Comment by martadinata666** [comment]
I see, i will drop this PR, and do new PR will default to alpine. And for the top level dockerfile let see what i can improve.

**Pull request closed without merging**
