### PR TITLE
Add example for Gitea's simple auth mode

### PR DESCRIPTION
**Pull request by rexzhang**
test on:
- LLDAP 0.4.1
- Gitea 1.18.3

### CODE REVIEW

**Comment by nitnelave** [comment]
I'm confused. What's the difference between the added configuration and the existing one?

**Comment by rexzhang** [comment]
Avoid `admin` account password leakage

**Comment by nitnelave** [comment]
Sorry, I'm not familiar with gitea and its config. How does the previous configuration leak the admin password, and how does this one prevent it?

**Comment by rexzhang** [comment]
In the BindDN mode, we need to fill the admin account's bind password of LLDAP into Gitea's config. In the simple auth mode, this isn't necessary.

**Comment by nitnelave** [comment]
Okay, I see the point. I had a closer look at the proposed config, but it's exactly the same as the one before, only without the bind DN and password, correct? In that case we can just make a note about simple auth without repeating all the settings.

**Comment by rexzhang** [comment]
Ok, It's updated

**Comment by nitnelave** [comment]
Thanks!

**Comment by benisai** [comment]
Here ya go. Select ldap-simple in Gitea.

Screenshot 2024-09-03 at 5 34 57 PM

Screenshot 2024-09-03 at 5 35 09 PM

Screenshot 2024-09-03 at 5 35 18 PM

**Review by nitnelave — APPROVED** [review]
Thanks!

**Pull request merged**
